### ISSUE TITLE
Discussion about Lighthouse points

### ISSUE THREAD

**Issue by MityaDementiy** [Halo-Lab/non-functional-requirements#2]
Hi, @koalko! 
I'd like to discuss Lighthouse points goals in [Performance chapter](https://github.com/Halo-Lab/non-functional-requirements/blob/main/Performance/Performance.md).

From my point of view Lighthouse and other similar tools are good indicators of web pages health. But I'm afraid that targeting the exact number of points, e.g. 95 or 100, is too expensive and not always useful. 

My proposal is to set minimal requirements to green zone for desktop (from 90 to 100 points) and yellow zone for mobiles. And if particular project/client needs more exact Lighthouse numbers, we can do as dedicated task.

What do you think about it?

**Comment by koalko** [comment]
Totally makes sense, thanks!
I will make corrections a bit later.
